### ISSUE TITLE
Popcorn on python 3

### ISSUE THREAD

**Issue by 1Coleman** [brielin/Popcorn#13]
I am trying to install popcorn on mac and running into problems. 

for i in xrange(int(np.ceil(bed.sid_count/s))):
NameError: name 'xrange' is not defined

**Comment by brielin** [comment]
Hi 1Coleman,

popcorn doesn't work in Python 3 because one of the dependencies (pysnptools) hasn't been ported to Python 3. There are a few more minor 2->3 syntax changes. I can't promise I will have time to port this to Python 3 anytime soon, but you are welcome to fork or submit a PR and try yourself.

Cheers,
Brielin
